### ISSUE TITLE
Typescript error, yarn dev

### ISSUE THREAD

**Issue by andreievg** [openmsupply/conforma-server#69]
Fresh clone of repo, node v14.8.0, `yarn install` then `yarn dev`:
```
node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/components/triggersAndActions.ts:90:66 - error TS2559: Type 'PostgresDB' has no properties in common with type 'IParameters'.

90     const condition = await evaluateExpression(action.condition, PostgresDB)
                                                                    ~~~~~~~~~~
src/components/triggersAndActions.ts:99:9 - error TS2559: Type 'PostgresDB' has no properties in common with type 'IParameters'.

99         PostgresDB
           ~~~~~~~~~~

    at createTSError (application-manager-server/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (application-manager-server/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (application-manager-server/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (application-manager-server/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (application-manager-server/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Object.require.extensions.<computed> [as .ts] (application-manager-server/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)

```

**Comment by CarlosNZ** [comment]
This is due to an inconsistency introduced by changes made to the Postgres database abstraction layer. Is fixed in later branches due to be merged soon.
